package com.droolsinaction.gift;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Gift implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String customer;

	public Gift() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getCustomer() {
		return this.customer;
	}

	public void setCustomer(java.lang.String customer) {
		this.customer = customer;
	}

	public Gift(java.lang.String name, java.lang.String customer) {
		this.name = name;
		this.customer = customer;
	}

}