package com.droolsinaction.loanapplication;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private int age;
	private int creditScore;
	private boolean eligible;
	private double monthlyIncome;
	private long yearlyIncome;

	public Applicant() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public int getCreditScore() {
		return this.creditScore;
	}

	public void setCreditScore(int creditScore) {
		this.creditScore = creditScore;
	}

	public double getMonthlyIncome() {
		return this.monthlyIncome;
	}

	public void setMonthlyIncome(double monthlyIncome) {
		this.monthlyIncome = monthlyIncome;
	}

	public long getYearlyIncome() {
		return this.yearlyIncome;
	}

	public void setYearlyIncome(long yearlyIncome) {
		this.yearlyIncome = yearlyIncome;
	}

	public boolean isEligible() {
		return this.eligible;
	}

	public void setEligible(boolean eligible) {
		this.eligible = eligible;
	}

	public Applicant(java.lang.String name, int age, int creditScore,
			boolean eligible, double monthlyIncome, long yearlyIncome) {
		this.name = name;
		this.age = age;
		this.creditScore = creditScore;
		this.eligible = eligible;
		this.monthlyIncome = monthlyIncome;
		this.yearlyIncome = yearlyIncome;
	}

	@Override
	public String toString() {
		return "Applicant [age=" + age + ", creditScore=" + creditScore + ", eligible=" + eligible + ", monthlyIncome="
				+ monthlyIncome + ", name=" + name + ", yearlyIncome=" + yearlyIncome + "]";
	}

}