package com.droolsinaction.loanapplication;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Loan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private long amount;
	private boolean approved;
	private java.lang.String comment;
	private int duration;
	private double interestRate;
	private double monthlyRepayment;

	public Loan() {
	}

	public long getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

	public boolean isApproved() {
		return this.approved;
	}

	public void setApproved(boolean approved) {
		this.approved = approved;
	}

	public java.lang.String getComment() {
		return this.comment;
	}

	public void setComment(java.lang.String comment) {
		this.comment = comment;
	}

	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public double getInterestRate() {
		return this.interestRate;
	}

	public void setInterestRate(double interestRate) {
		this.interestRate = interestRate;
	}

	public double getMonthlyRepayment() {
		return this.monthlyRepayment;
	}

	public void setMonthlyRepayment(double monthlyRepayment) {
		this.monthlyRepayment = monthlyRepayment;
	}

	public Loan(long amount, boolean approved, java.lang.String comment,
			int duration, double interestRate, double monthlyRepayment) {
		this.amount = amount;
		this.approved = approved;
		this.comment = comment;
		this.duration = duration;
		this.interestRate = interestRate;
		this.monthlyRepayment = monthlyRepayment;
	}

	@Override
	public String toString() {
		return "Loan [amount=" + amount + ", approved=" + approved + ", comment=" + comment + ", duration=" + duration
				+ ", interestRate=" + interestRate + ", monthlyRepayment=" + monthlyRepayment + "]";
	}
	
}