package com.droolsinaction.recommendation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OperatingSystem implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String osName;

	public OperatingSystem() {
	}

	public java.lang.String getOsName() {
		return this.osName;
	}

	public void setOsName(java.lang.String osName) {
		this.osName = osName;
	}

	public OperatingSystem(java.lang.String osName) {
		this.osName = osName;
	}

}