package com.droolsinaction.recommendation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Recommendation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String make;
	private java.lang.String model;

	public Recommendation() {
	}

	public java.lang.String getMake() {
		return this.make;
	}

	public void setMake(java.lang.String make) {
		this.make = make;
	}

	public java.lang.String getModel() {
		return this.model;
	}

	public void setModel(java.lang.String model) {
		this.model = model;
	}

	public Recommendation(java.lang.String make, java.lang.String model) {
		this.make = make;
		this.model = model;
	}

}