package com.droolsinaction.recommendation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TravelProfile implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private boolean noTravel;
	private int travelPercent;

	public TravelProfile() {
	}

	public boolean isNoTravel() {
		return this.noTravel;
	}

	public void setNoTravel(boolean noTravel) {
		this.noTravel = noTravel;
	}

	public int getTravelPercent() {
		return this.travelPercent;
	}

	public void setTravelPercent(int travelPercent) {
		this.travelPercent = travelPercent;
	}

	public TravelProfile(boolean noTravel, int travelPercent) {
		this.noTravel = noTravel;
		this.travelPercent = travelPercent;
	}

}