package com.droolsinaction.promotion;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Discount implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String description;
	private double rate;

	public Discount() {
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public double getRate() {
		return this.rate;
	}

	public void setRate(double rate) {
		this.rate = rate;
	}

	public Discount(java.lang.String description, double rate) {
		this.description = description;
		this.rate = rate;
	}

}